name: Run Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - run: docker run -td --name testenv bossraths/samplerepo:latest
    - run: docker cp . testenv:/newwwwww
    - run: docker exec -it testenv ls ./newwwwww
